language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wootoodoo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wootoodoo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react3"
  env: "DockerReact3-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-535833284079"
  bucket_path: "docker-react2"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY