language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wootoodoo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wootoodoo/docker-react npm run test